swagger: '2.0'
info:
  title: HTML_INJECTION BY MCHKLT
  description: |
    <h1>Hello World From <b>HTML</b></h1>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /MCHKLT:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - MCHKLT_HTML_INJECTION
      operationId: findAccounts
      summary: Finds all accounts
  '/hack/hachid/{id}':
    delete:
      parameters:
        - description: |
            <h1>Hello World From <b>HTML</b></h1>
          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
